/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package content;

import java.sql.*;

import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author gargi
 */
public class editappointment extends javax.swing.JPanel  {
 private final String DB_URL ="jdbc:mysql://localhost:3306/gargi";
    private final String USER="root";
    private final String PASS ="gargi*1995";
    
  
   int id;
   
   String id1;
   private static String name1;
    public editappointment(String idd) {
        initComponents();
        setSize(100,100);
        this.id1=idd;
        System.out.println("inside");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        status1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        note1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        disease = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 241, 238));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Disease :");

        jLabel2.setBackground(new java.awt.Color(255, 174, 61));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Notes :");

        status1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Change Status", "Booked", "Cancelled", "Done", "Pending" }));
        status1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        note1.setColumns(20);
        note1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        note1.setRows(5);
        jScrollPane1.setViewportView(note1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Status :");

        jLabel4.setBackground(new java.awt.Color(255, 174, 61));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Patient Name  :");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        disease.setBackground(new java.awt.Color(255, 255, 255));
        disease.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(255, 174, 61));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        edit.setText("Edit");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(status1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disease, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(close)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disease, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(edit)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents
 @Override
    public void setName(String name11){
        this.name1=name11;
         System.out.println("inside"+name1);
         this.getinfo();
    }
    public void getinfo(){
        
         try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);){
        
String sql="SELECT * FROM patient where p_name=?";
System.out.println("Here"+name1);
           PreparedStatement stmt=conn.prepareStatement(sql);
           stmt.setString(1,name1);
           ResultSet rs = stmt.executeQuery();

        // Print rows
        while (rs.next()) {
           
           String disease1 = rs.getString("disease");
           id=rs.getInt("p_id");
           name.setText(name1);
           disease.setText(disease1);
           
           
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
        
        
    }
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        if(!(note1.getText()).isEmpty() &&  !(status1.getItemAt(status1.getSelectedIndex())).equals("Change Status")){
         try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);){
        
           String sql="Update appointment Set status=?,notes=?  where p_id=?";
           PreparedStatement stmt=conn.prepareStatement(sql);
           stmt.setString(1,(String)(status1.getItemAt(status1.getSelectedIndex())));
           stmt.setString(2,note1.getText());
           stmt.setInt(3,id);
           
           stmt.executeUpdate();
           JOptionPane.showMessageDialog(this,"Appointment details Updated");
           refresh(); 

       
        
           
           
        
    } catch (SQLException e) {
        System.out.print(e);
    }
        }
        else{
            JOptionPane.showMessageDialog(this,"Please Enter Details Properly!");
        }
        
    }//GEN-LAST:event_editActionPerformed
    public void refresh(){
        note1.setText("");
        status1.setSelectedIndex(0);
      
    }
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
      appointment.g1.setVisible(true);
       appointment.ep.setVisible(false);
        
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel disease;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextArea note1;
    private javax.swing.JComboBox<String> status1;
    // End of variables declaration//GEN-END:variables
}
